services:
  db:
    image: postgres:15.0-bullseye
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  node:
    build: ./oclif/
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    # For debugging, uncomment:
    # stdin_open: true
    # tty: true
    depends_on:
      db:
        condition: service_healthy

  pgadmin4:
    image: dpage/pgadmin4:6.15
    restart: always
    ports:
      - 5433:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
    depends_on:
      - "db"
    profiles:
      - debug

volumes:
  db_volume:
