trigger:
    - main

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: Gradle@2
      inputs:
          gradleWrapperFile: "gradlew"
          tasks: "clean build test"
          publishJUnitResults: true
          testResultsFiles: "**/test-results/**/*.xml"
