trigger:
    - main

pool:
    vmImage: "ubuntu-latest"

steps:
    - task: Gradle@2
      inputs:
          gradleWrapperFile: "spring/gradlew"
          workingDirectory: "spring" # set the working directory to the spring folder
          tasks: "clean build test"
          publishJUnitResults: true
          testResultsFiles: "**/test-results/**/*.xml"
